
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  errors:
    deprecated_member_use: ignore
#   exclude:
#     - path/to/excluded/files/**
