name: bones_ui_bootstrap
description: Adds Bootstrap 4+ support to Dart package bones_ui, allowing use of Bootstrap components and CSS.
version: 2.0.7
homepage: https://github.com/Colossus-Services/bones_ui_bootstrap

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  bones_ui: ^2.0.13
  swiss_knife: ^3.1.1
  amdjs: ^2.0.3
  dom_tools: ^2.1.1
  dom_builder: ^2.0.9
  intl_messages: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  sass_builder: ^2.1.3 # To automatically build SCSS files.
  lints: ^2.0.0
  dependency_validator: ^3.2.0
  test: ^1.21.3

#dependency_overrides:
#  bones_ui:
#    path: ../bones_ui
#  swiss_knife:
#    path: ../swiss_knife
#  amdjs:
#    path: ../amdjs
#  dom_tools:
#    path: ../dom_tools
#  intl_messages:
#    path: ../intl_messages
