name: bones_ui_bootstrap
description: Adds Bootstrap 4+ support to Dart package bones_ui, allowing use of Bootstrap components and CSS.
version: 3.0.0-beta.1
homepage: https://github.com/Colossus-Services/bones_ui_bootstrap

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  bones_ui: ^3.0.0-beta.2
  swiss_knife: ^3.2.3
  amdjs: ^3.0.0-beta.2
  dom_tools: ^3.0.0-beta.4
  dom_builder: ^3.0.0-beta.2
  intl_messages: ^2.3.4
  web: ^1.1.0
  web_utils: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.1
  sass_builder: ^2.2.1 # To automatically build SCSS files.
  lints: ^5.1.1
  dependency_validator: ^3.2.3
  test: ^1.25.15

#dependency_overrides:
#  bones_ui:
#    path: ../bones_ui
#  swiss_knife:
#    path: ../swiss_knife
#  amdjs:
#    path: ../amdjs.dart
#  dom_tools:
#    path: ../dom_tools
#  web_utils:
#    path: ../web_utils
#  intl_messages:
#    path: ../intl_messages
