name: bones_ui_bootstrap
description: Adds Bootstrap support to Dart package bones_ui, allowing use of Bootstrap components and CSS.
version: 1.0.0
homepage: https://github.com/Colossus-Services/bones_ui_bootstrap

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bones_ui: ^1.0.9
    #path: ../bones_ui
  swiss_knife: ^2.5.2
    #path: ../swiss_knife
  amdjs: 1.0.3
    #path: ../amdjs
  dom_tools: ^1.3.1
    #path: ../dom_tools
  intl_messages: ^1.1.8
    #path: ../intl_messages

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7
