name: bones_ui_bootstrap
description: Adds Bootstrap 4+ support to Dart package bones_ui, allowing use of Bootstrap components and CSS.
version: 1.1.1
homepage: https://github.com/Colossus-Services/bones_ui_bootstrap

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bones_ui: ^1.1.0
    #path: ../bones_ui
  swiss_knife: ^2.5.18
    #path: ../swiss_knife
  amdjs: ^1.0.7
    #path: ../amdjs
  dom_tools: ^1.3.15
    #path: ../dom_tools
  intl_messages: ^1.1.12
    #path: ../intl_messages


dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.2
  test: ^1.15.4
