name: bones_ui_bootstrap
description: Adds Bootstrap 4+ support to Dart package bones_ui, allowing use of Bootstrap components and CSS.
version: 2.0.1
homepage: https://github.com/Colossus-Services/bones_ui_bootstrap

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bones_ui: ^2.0.1
  swiss_knife: ^3.0.6
  amdjs: ^2.0.1
  dom_tools: ^2.0.1
  intl_messages: ^2.0.1


dev_dependencies:
  #build_runner: ^1.10.0
  #build_web_compilers: ^2.11.0
  pedantic: ^1.11.0
  test: ^1.16.7

#dependency_overrides:
#  bones_ui:
#    path: ../bones_ui
#  swiss_knife:
#    path: ../swiss_knife
#  amdjs:
#    path: ../amdjs
#  dom_tools:
#    path: ../dom_tools
#  intl_messages:
#    path: ../intl_messages
