name: bones_ui_bootstrap
description: Adds Bootstrap 4+ support to Dart package bones_ui, allowing use of Bootstrap components and CSS.
version: 2.3.0
homepage: https://github.com/Colossus-Services/bones_ui_bootstrap

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bones_ui: ^2.5.0
  swiss_knife: ^3.2.0
  amdjs: ^2.0.3
  dom_tools: ^2.3.0
  dom_builder: ^2.2.2
  intl_messages: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  sass_builder: ^2.2.1 # To automatically build SCSS files.
  lints: ^3.0.0
  dependency_validator: ^3.2.3
  test: ^1.25.2

#dependency_overrides:
#  bones_ui:
#    path: ../bones_ui
#  swiss_knife:
#    path: ../swiss_knife
#  amdjs:
#    path: ../amdjs
#  dom_tools:
#    path: ../dom_tools
#  intl_messages:
#    path: ../intl_messages
